spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        #healthCheckPath: ${management.contextPath}/health
        heartbeat:
          enabled: true
        #healthCheckPath: /health
        healthCheckInterval: 15s
#        instance-id:  ${spring.application.name}-${random.int[10000,99999]}
        enabled: true
        health-check-path: /actuator/health
        service-name: service-producer
      enabled: true
  application:
    name: spring-cloud-consul-producer
server:
  port: 8888

